name: Wen-Hao Lue
pygments: true
relative_permalinks: false
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'config.rb', 'Rakefile',
  'Procfile.local']

google_analytics:
  account: UA-12654814-1
disqus:
  id: wlue
